In [2]:
import pandas
import pandas as pd
import sklearn.model_selection
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt

data = pandas.read_csv("StudentPerformanceFactorsPuhas.csv", sep=";")

data

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6373,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6374,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6375,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6376,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6377,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [3]:
data = pandas.get_dummies(data, columns=data.columns[(data.dtypes == 'object') | (data.dtypes == 'category')])
data

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score,Parental_Involvement_High,Parental_Involvement_Low,Parental_Involvement_Medium,...,Learning_Disabilities_No,Learning_Disabilities_Yes,Parental_Education_Level_College,Parental_Education_Level_High School,Parental_Education_Level_Postgraduate,Distance_from_Home_Far,Distance_from_Home_Moderate,Distance_from_Home_Near,Gender_Female,Gender_Male
0,23,84,7,73,0,3,67,False,True,False,...,True,False,False,True,False,False,False,True,False,True
1,19,64,8,59,2,4,61,False,True,False,...,True,False,True,False,False,False,True,False,True,False
2,24,98,7,91,2,4,74,False,False,True,...,True,False,False,False,True,False,False,True,False,True
3,29,89,8,98,1,4,71,False,True,False,...,True,False,False,True,False,False,True,False,False,True
4,19,92,6,65,3,4,70,False,False,True,...,True,False,True,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6373,25,69,7,76,1,2,68,True,False,False,...,True,False,False,True,False,False,False,True,True,False
6374,23,76,8,81,3,2,69,True,False,False,...,True,False,False,True,False,False,False,True,True,False
6375,20,90,6,65,3,2,68,False,False,True,...,True,False,False,False,True,False,False,True,True,False
6376,10,86,6,91,2,3,68,True,False,False,...,True,False,False,True,False,True,False,False,True,False
6377,15,67,9,94,0,4,64,False,False,True,...,True,False,False,False,True,False,False,True,False,True

In [4]:
x = data.drop("Exam_Score", axis=1)
y = data["Exam_Score"]
print(x.shape,
y.shape)
X_train_val, X_test, y_train_val, y_test = sklearn.model_selection.train_test_split(x, y, train_size=0.8)
X_train, X_val, y_train, y_val = sklearn.model_selection.train_test_split(X_train_val, y_train_val, train_size=0.8)

(6378, 40) (6378,)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

model = KNeighborsClassifier(n_neighbors=10, metric="euclidean")
model.fit(X_train, y_train)
accuracy = accuracy_score(y_test, model.predict(X_test))
accuracy

0.19827586206896552

In [6]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(criterion="entropy")
model.fit(X_train, y_train)
accuracy = accuracy_score(y_test, model.predict(X_test))
accuracy

0.19905956112852666

In [7]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, max_depth=10)
model.fit(X_train, y_train)
accuracy = accuracy_score(y_test, model.predict(X_test))
accuracy

0.2249216300940439

In [11]:
from sklearn.svm import SVC

model = SVC(kernel="linear", degree=2, gamma="auto")
model.fit(X_train, y_train)
accuracy = accuracy_score(y_val, model.predict(X_val))
accuracy

0.8188050930460333

In [24]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import pandas as pd

model = RandomForestRegressor()
model.fit(X_train, y_train)
pred = model.predict(X_val)
mse = mean_squared_error(y_val, pred)
print(f'Mean Squared Error: {mse}')

importances = model.feature_importances_
feature_importance_df = pd.DataFrame({"Feature": X_train.columns, "Importance": importances})
print(feature_importance_df)

Mean Squared Error: 3.5969939275220373
                                  Feature  Importance
0                           Hours_Studied    0.239291
1                              Attendance    0.381078
2                             Sleep_Hours    0.023652
3                         Previous_Scores    0.081617
4                       Tutoring_Sessions    0.026983
5                       Physical_Activity    0.027437
6               Parental_Involvement_High    0.015977
7                Parental_Involvement_Low    0.014159
8             Parental_Involvement_Medium    0.003578
9                Access_to_Resources_High    0.014993
10                Access_to_Resources_Low    0.014225
11             Access_to_Resources_Medium    0.004837
12          Extracurricular_Activities_No    0.005692
13         Extracurricular_Activities_Yes    0.003386
14                  Motivation_Level_High    0.007459
15                   Motivation_Level_Low    0.006541
16                Motivation_Level_Medium    0.003782
17                     Internet_Access_No    0.003371
18                    Internet_Access_Yes    0.003312
19                     Family_Income_High    0.008704
20                      Family_Income_Low    0.006332
21                   Family_Income_Medium    0.003791
22                   Teacher_Quality_High    0.007810
23                    Teacher_Quality_Low    0.003812
24                 Teacher_Quality_Medium    0.004986
25                    School_Type_Private    0.002371
26                     School_Type_Public    0.003199
27                Peer_Influence_Negative    0.006502
28                 Peer_Influence_Neutral    0.005221
29                Peer_Influence_Positive    0.007047
30               Learning_Disabilities_No    0.004816
31              Learning_Disabilities_Yes    0.004667
32       Parental_Education_Level_College    0.005657
33   Parental_Education_Level_High School    0.006441
34  Parental_Education_Level_Postgraduate    0.011365
35                 Distance_from_Home_Far    0.007507
36            Distance_from_Home_Moderate    0.003506
37                Distance_from_Home_Near    0.006814
38                          Gender_Female    0.004140
39                            Gender_Male    0.003942

In [9]:
data["Exam_Score"].value_counts()

Exam_Score
68     738
66     722
67     692
65     650
69     599
70     526
64     478
71     398
63     350
72     298
62     261
61     166
73     133
74     102
60      75
75      48
59      39
58      21
76      16
80       5
77       5
94       4
86       4
82       4
78       4
57       4
84       3
79       3
89       3
98       3
88       3
97       3
95       2
93       2
87       2
99       2
92       2
83       1
100      1
55       1
101      1
91       1
96       1
85       1
56       1
Name: count, dtype: int64